# name: CI Workflow

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   # lint:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: actions/checkout@v4
#   #     - uses: oven-sh/setup-bun@v1
#   #     - run: bun install
#   #     - run: bun run lint

#   # test:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: actions/checkout@v4
#   #     - uses: oven-sh/setup-bun@v1
#   #     - run: bun install
#   #     - run: bun run test

#   # version-check:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: actions/checkout@v4
#   #       with:
#   #         fetch-depth: 0
#   #     - uses: EndBug/version-check@v2
#   #       with:
#   #         diff-search: true
#   #         file-name: package.json
#   #         token: ${{ github.TOKEN }}

#   # approval:
#   #   runs-on: ubuntu-latest
#   #   needs: [lint, test, version-check]
#   #   permissions:
#   #     contents: read
#   #     issues: write
#   #   if: github.event_name == 'pull_request'
#   #   steps:
#   #     - uses: trstringer/manual-approval@v1
#   #       with:
#   #         secret: ${{ github.TOKEN }}
#   #         approvers: ${{ github.actor }}
#   #         minimum-approvals: 1
#   #         issue-title: "Publishing Pre-Release"
#   #         issue-body: "Please approve or deny the creation of version the pre-release."
#   #         # issue-body-file-path: relative/file_path/wrt/repo/root
#   #         exclude-workflow-initiator-as-approver: false
#   #         fail-on-denial: true
#   #         additional-approved-words: ''
#   #         additional-denied-words: ''

#   notify:
#     runs-on: ubuntu-latest
#     # needs: [approval]
#     if: github.event_name == 'pull_request'
#     permissions:
#       contents: read
#       issues: write
#       pull-requests: write
#     steps:
#       - uses: actions/github-script@v7
#         with:
#           script: |
#             github.rest.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: 'Approval granted! You can now trigger the CD workflow here: https://github.com/${{ github.repository }}/actions/workflows/cd.yml'
#             })
name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"